// T3.17 — SPEC-3-017: template do contrato de prestação de serviços da Vibratto.
// Estrutura das 9 cláusulas do contrato real da Felicidade Collective (insumo da CEO,
// 13/09): Objeto (com implantação + diagnóstico tributário + alçada bancária),
// Obrigações, Prazo (12 meses, renovação automática), Preço (implantação em 2 parcelas
// + mensalidade com escalonamento + parcela anual em novembro + IPCA), Rescisão (30 dias),
// Sigilo/LGPD, Disposições gerais, Foro (SP).
// NENHUM dado de cliente no template — só placeholders nomeados {{chave}}.
// Placeholders: VIGENCIA_INICIO, RAZAO_SOCIAL_PRESTADOR, CNPJ_PRESTADOR, SEDE_PRESTADOR,
// REP_PRESTADOR, RAZAO_SOCIAL_CONTRATANTE, CNPJ_CONTRATANTE, SEDE_CONTRATANTE,
// REP_CONTRATANTE, ESCOPO_SERVICOS, IMPLANTACAO_PARCELA_1, IMPLANTACAO_PARCELA_2,
// MENSALIDADE_INICIAL, MENSALIDADE_POS_ESCALONAMENTO, PARCELA_ANUAL_MES,
// REAJUSTE_INDICE, FORO.

var TEMPLATE_CONTRATO_VIBRATTO = [
  'CONTRATO DE PRESTAÇÃO DE SERVIÇOS DE BPO FINANCEIRO, CONTROLADORIA E GESTÃO FINANCEIRA',
  '',
  '{{RAZAO_SOCIAL_PRESTADOR}}, pessoa jurídica de direito privado, inscrita no CNPJ sob o nº {{CNPJ_PRESTADOR}}, com sede em {{SEDE_PRESTADOR}}, neste ato representada por {{REP_PRESTADOR}}, doravante denominada PRESTADORA, e, de outro lado, {{RAZAO_SOCIAL_CONTRATANTE}}, pessoa jurídica de direito privado, inscrita no CNPJ sob o nº {{CNPJ_CONTRATANTE}}, com sede em {{SEDE_CONTRATANTE}}, neste ato representada por {{REP_CONTRATANTE}}, doravante denominada CONTRATANTE.',
  '',
  'As partes têm, entre si, justo e acertado o presente Contrato de Prestação de Serviços, que se regerá pelas cláusulas seguintes e pelas condições descritas no presente.',
  '',
  'CLÁUSULA 1ª — DO OBJETO',
  '',
  '1.1. O presente contrato tem como objeto a prestação, pela PRESTADORA, dos seguintes serviços:',
  '',
  '{{ESCOPO_SERVICOS}}',
  '',
  '1.2. A prestação dos serviços inclui a implantação das rotinas objeto deste contrato, compreendendo a criação dos acessos e da estrutura operacional, a análise das informações financeiras da CONTRATANTE e o diagnóstico, definição e validação dos processos do dia a dia, com apresentação do sistema de gestão.',
  '',
  '1.3. A prestadora realizará diagnóstico tributário preliminar das operações da CONTRATANTE, sem emissão de parecer contábil, fiscal ou jurídico — eventuais conclusões desse diagnóstico serão sempre validadas com o profissional responsável da CONTRATANTE.',
  '',
  '1.4. A execução de pagamentos, transferências e movimentações bancárias em nome da CONTRATANTE dependerá de alçada expressamente autorizada por ela, registrada por escrito (e-mail ou sistema), com limites definidos pelas partes.',
  '',
  '1.5. Os serviços serão prestados de forma remota e/ou presencial, conforme a necessidade de cada rotina, sem exclusividade para qualquer das partes.',
  '',
  '1.6. A PRESTADORA não se obriga a resultados de mercado, concessão de crédito ou qualquer resultado econômico futuro — sua obrigação é de meio, com execução diligente das rotinas contratadas.',
  '',
  'CLÁUSULA 2ª — DAS OBRIGAÇÕES DA PRESTADORA',
  '',
  '2.1. Executar as rotinas contratadas conforme os procedimentos operacionais acordados, com rastreabilidade de cada passo registrado.',
  '2.2. Entregar relatórios e leituras de decisão nos prazos acordados, com números fiéis aos registros — sem arredondamento ou apresentação que induza conclusão equivocada.',
  '2.3. Manter sigilo sobre todas as informações da CONTRATANTE, durante e após a vigência, e tratar dados pessoais em conformidade com a Lei Geral de Proteção de Dados (Lei nº 13.709/2018).',
  '2.4. Comunicar prontamente a CONTRATANTE qualquer fato que impeça ou comprometa a execução das rotinas.',
  '',
  'CLÁUSULA 3ª — DAS OBRIGAÇÕES DA CONTRATANTE',
  '',
  '3.1. Fornecer, no prazo acordado, os acessos, documentos e informações necessários à execução dos serviços, inclusive credenciais de sistemas por meio seguro.',
  '3.2. Designar responsável pela validação de rotinas, autorizações e aprovações.',
  '3.3. Efetuar os pagamentos nas datas pactuadas na Cláusula 4ª.',
  '3.4. Manter a contabilidade e as obrigações fiscais com profissional próprio ou contratado, não constituindo objeto deste contrato a substituição dessas funções, salvo disposição expressa em contrário no escopo.',
  '',
  'CLÁUSULA 4ª — DO PRAZO',
  '',
  '4.1. O presente contrato terá vigência de 12 (doze) meses, iniciando-se em {{VIGENCIA_INICIO}}, renovando-se automaticamente por períodos sucessivos de 12 (doze) meses, salvo denúncia de qualquer das partes.',
  '',
  'CLÁUSULA 5ª — DO PREÇO E DAS CONDIÇÕES DE PAGAMENTO',
  '',
  '5.1. Pela execução dos serviços, a CONTRATANTE pagará à PRESTADORA:',
  '',
  '{{CONDICOES_FINANCEIRAS}}',
  '',
  '5.2. Os valores serão reajustados anualmente pelo {{REAJUSTE_INDICE}} ou pelo índice legal que vier a substituí-lo, incidindo a partir da data-base.',
  '5.3. A implantação é cobrada uma única vez, nas parcelas indicadas acima, e não é reajustada nem devolvida em caso de rescisão por culpa da CONTRATANTE.',
  '5.4. Pagamentos em atraso acarretarão multa de 2% (dois por cento), juros de mora de 1% (um por cento) ao mês e correção monetária, além da faculdade de suspensão dos serviços após aviso prévio de 5 (cinco) dias úteis.',
  '',
  'CLÁUSULA 6ª — DA RESCISÃO',
  '',
  '6.1. Qualquer das partes poderá rescindir este contrato mediante aviso prévio de 30 (trinta) dias, por escrito.',
  '6.2. A rescisão por culpa da CONTRATANTE não exonera o pagamento dos serviços prestados até a data do efetivo desligamento, nem das parcelas de implantação vencidas.',
  '6.3. Rescindido o contrato, a PRESTADORA entregará à CONTRATANTE os documentos, planilhas e registros em seu poder, no prazo de até 15 (quinze) dias.',
  '',
  'CLÁUSULA 7ª — DO SIGILO E DA PROTEÇÃO DE DADOS',
  '',
  '7.1. As partes manterão sigilo sobre todas as informações comerciais, financeiras e cadastrais trocadas na execução deste contrato.',
  '7.2. O tratamento de dados pessoais observará a Lei nº 13.709/2018 (LGPD), limitando-se às finalidades da execução contratual.',
  '',
  'CLÁUSULA 8ª — DAS DISPOSIÇÕES GERAIS',
  '',
  '8.1. Este contrato não gera vínculo empregatício, societário ou de representação entre as partes.',
  '8.2. A PRESTADORA não responde por obrigações tributárias, trabalhistas ou fiscais da CONTRATANTE, cuja titularidade permanece com ela.',
  '8.3. Nenhuma renúncia de direito será presumida; as alterações deste contrato somente valerão por aditivo escrito assinado pelas partes.',
  '',
  'CLÁUSULA 9ª — DO FORO',
  '',
  '9.1. Fica eleito o foro da comarca de {{FORO}} para dirimir quaisquer controvérsias oriundas deste contrato, com renúncia a qualquer outro, por mais privilegiado que seja.',
  '',
  'E, por estarem justas e contratadas, as partes assinam o presente instrumento em 2 (duas) vias de igual teor.',
  '',
  'São Paulo, {{DATA_ASSINATURA}}.',
  '',
  '',
  '_______________________________________',
  '{{RAZAO_SOCIAL_PRESTADOR}}',
  '',
  '',
  '_______________________________________',
  '{{RAZAO_SOCIAL_CONTRATANTE}}',
].join('\n')
